Frontpage  so me block
DieMannschaft/hifi pull request #31
Opened 2020-09-16 23:18 UTC by Sirius-33

ready for review

2020-09-17 07:46 UTC, Sirius-33 commented on assets/css/frontpage__SoMeBlock.css
> +    padding: 141px 0;
jeg har lige opdaget, at jeg har skrevet pixel her - rettes

2020-09-17 07:46 UTC, Sirius-33 commented on assets/css/frontpage__SoMeBlock.css
> +    padding: 141px 0;
rettes til rem

2020-09-17 07:46 UTC, Sirius-33 commented on assets/css/frontpage__SoMeBlock.css
> +    padding: 141px 0;
rettes til rem

2020-09-17 07:57 UTC, MadsHaerup commented
Skal du ikke også tilføje billederne bag so-me ikonerne?
udover det så mener jeg," justify-content: space-evenly;" skal fjernes, for når der kommer billeder på er felterne meget smalle.
Jeg forstår godt din ide med grid-templates, men efter min forståelse skal det bruges til det overordnet layout, altså du kalder hele dit komponent et navn (so-me-block) også i index filen laver vi et grid-template-layout hvor so-me-block indgår. For i dette tilfælde kan du bare lave grid-template-column: repeat(3, 1fr) i stedet for at navngive alle felter. Håber det giver mening

2020-09-17 09:14 UTC, Sirius-33 commented
> Skal du ikke også tilføje billederne bag so-me ikonerne?
> udover det så mener jeg," justify-content: space-evenly;" skal fjernes, for når der kommer billeder på er felterne meget smalle.
> Jeg forstår godt din ide med grid-template-area, men efter min forståelse skal det bruges til det overordnet layout, altså du kalder hele dit komponent et navn (so-me-block) også i index filen laver vi et grid-template-area layout hvor so-me-block indgår. For i dette tilfælde kan du bare lave grid-template-column: repeat(3, 1fr) i stedet for at navngive alle felter. Håber det giver mening.
> Edit:
> Der mangler også et parameter i din responsive grid-template-columns: repeat(minmax(40px, 33.33vw))
> Enten: repeat(**3**, minmax(40px, 33.33vw)) eller repeat(**auto-fit**, minmax(40px, 33.33vw))
> Der mangler dog stadig lidt finpudsning på den responsive del

yup mangler det parameter med 3, godt spottet. Jeg har undgået 3, 1fr fordi at det ikke giver grided den samme struktur og det flytter på sig. Ved at specificere deres placering sikre jeg, at de bliver i boksene.

Space-evenly skulle ikke have noget problem med et baggrundsbillede på en div som er idéen til når vi sætter billeder på. Dette vil jeg gøre efter kl 12, når jeg er hjemme foran pc'en. Så tester jeg det der.

grid-template-areas kan bruges som man lyster, den bruges normalt til layout, men kan bruges på enkelte elementer også. 

Jeg får lige rettet og tak for god feedback 👍

2020-09-17 17:12 UTC, Sirius-33 commented
> 
> 
> Skal du ikke også tilføje billederne bag so-me ikonerne?
> udover det så mener jeg," justify-content: space-evenly;" skal fjernes, for når der kommer billeder på er felterne meget smalle.
> Jeg forstår godt din ide med grid-template-area, men efter min forståelse skal det bruges til det overordnet layout, altså du kalder hele dit komponent et navn (so-me-block) også i index filen laver vi et grid-template-area layout hvor so-me-block indgår. For i dette tilfælde kan du bare lave grid-template-column: repeat(3, 1fr) i stedet for at navngive alle felter. Håber det giver mening.
> Edit:
> Der mangler også et parameter i din responsive grid-template-columns: repeat(minmax(40px, 33.33vw))
> Enten: repeat(**3**, minmax(40px, 33.33vw)) eller repeat(**auto-fit**, minmax(40px, 33.33vw))
> Der mangler dog stadig lidt finpudsning på den responsive del

Du har ret i det med space evenly. Mellemrummet bliver underligt

2020-09-18 14:32 UTC, MadsHaerup requested changes

2020-09-18 14:32 UTC, MadsHaerup commented on assets/css/frontpage__SoMeBlock.css
> +    grid-template-columns: repeat( 3 minmax(40px, 33.33vw));
Rettelse: repeat( 3,minmax(40px, 33.33vw)); 
Facebook og twitter skal være runde Fontawesome Ikoner

Facebook:` <i class="fab fa-facebook"></i>`
Twitter: - findes åbenbart ikke som rundt. Det måske derfor du er gået med 3 firkantede?

Skal baggrundsbillderne ikke også stadig tilføjes nu? før det endelig merge.

2020-09-21 06:46 UTC, MadsHaerup approved these changes

2020-09-23 11:06 UTC, merged