Single product view knapper
DieMannschaft/hifi pull request #36
Opened 2020-09-17 07:46 UTC by elisabethasbaek

2020-09-17 19:46 UTC, Sirius-33 commented on assets/css/knapper.css
> +    font-size: 0.8rem;
font-size: 0.66vw;

Jeg tror næsten at den er i skabet, ellers kan du rette lidt til. Men dette skulle gerne løse dit media query problem, og gøre dem responsive. Så kan vi lige se hvordan det reagere når vi smider det hele ind på frontpage.html og evt kigge på media queries?

2020-09-17 19:49 UTC, Sirius-33 commented on assets/css/knapper.css
> +    max-width: 60vw;
Vi kan muligvis få brug for at lave dette om til rem i næste sprint, det kommer an på hvordan denne vw vil reagere inde i knappernes nye container på frontpage.html

2020-09-17 19:50 UTC, Sirius-33 commented on knapper.html
> +</html>
Clean kode + nem overskuelighed + godt arbejde - resten er småligheder vi kan tage under polish hvis de skulle opstå

2020-09-17 19:51 UTC, Sirius-33 requested changes
Naisu 👍 

Jeg har sendt et forslag til dit spørgsmål omkring media queries, så changes skyldes ikke fejl i koden. Ingen som jeg kan se i hvert fald.

2020-09-18 07:06 UTC, elisabethasbaek commented on assets/css/knapper.css
> +    max-width: 60vw;
Du kan have ret, det vil jeg være opmærksom på!

2020-09-18 07:06 UTC, elisabethasbaek commented on knapper.html
> +</html>
Thanks brooooo!

2020-09-18 07:08 UTC, elisabethasbaek commented on assets/css/knapper.css
> +    font-size: 0.8rem;
Det har jeg gjort nu, med den fontsize du foreslog!

2020-09-18 08:52 UTC, elisabethasbaek commented
Er den her så klar til at blive approved?

2020-09-18 10:55 UTC, Sirius-33 approved these changes
Smukt 👍

2020-09-23 12:05 UTC, merged