Venstre asides
DieMannschaft/hifi pull request #43
Opened 2020-09-18 08:20 UTC by Nadjaroemer

2020-09-18 10:18 UTC, Nadjaroemer commented
#43

2020-09-18 10:37 UTC, MadsHaerup commented
@Nadjaroemer Prisen wrapper under og baggrunden er ikke responsive, har kigget på det og foreslår at du gør således:
1)Ændre width til 25vw
2).venstre_aside_one - Fjerner padding 10vh / Tilføjer padding-left: 3vw;
3) .venstre_aside_one > a:first-of-type / tilføj margin-top: 3rem

2020-09-18 10:43 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    width: 20vw;
25vw

2020-09-18 10:44 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    padding: 10vh;
fjern + tilføj padding-left:  3vwM

2020-09-18 10:45 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    width: 20vw;
width: 25vw;

2020-09-18 10:48 UTC, MadsHaerup requested changes

2020-09-18 10:48 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    padding: 10vh;
fjern / tilføj padding-left: 3vw;

2020-09-18 10:48 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +.venstre_aside_one>a:first-of-type {
tilføj margin-top: 3rem

2020-09-18 10:50 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    color: #828D8A;
tilføj margin-top: 3rem

2020-09-18 10:56 UTC, MadsHaerup commented on venstre asides/venstre_asides.css
> +    text-transform: uppercase;
tilføj margin-top: 3rem;

2020-09-18 10:57 UTC, Nadjaroemer reviewed
Hej. Har ændret det hele. Tak for god feedback!

2020-09-21 06:57 UTC, Nadjaroemer commented
Det eneste jeg lige kom i tanken om er, at der jo egentlig ikke skal være width på, fordi de bliver jo sat ind i et grid, som har en størrelse...

2020-09-21 06:59 UTC, MadsHaerup approved these changes

2020-09-23 09:21 UTC, merged